version: '3'
services:
  oswe-atutor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: atutor-mysql
    ports:
      - "8080:80"
    command: "/bin/bash -c '/opt/lampp/lampp start && tail -f /dev/null'"
    networks:
      - atutor-network

networks:
  atutor-network:
